# Generated by Django 4.2.1 on 2023-06-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='resumen',
            field=models.TextField(null=True),
        ),
    ]
