# Generated by Django 4.2.1 on 2023-06-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_autor_imagen_url_autor_resumen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='imagen_url',
            new_name='foto',
        ),
    ]
