# Generated by Django 4.2.1 on 2023-06-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0004_alter_review_comentario_alter_review_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='valoracion',
        ),
    ]
