# Generated by Django 4.2.1 on 2023-06-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0005_remove_libro_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='valoracion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
